#!/usr/bin/env python3
"""Refresh the Website's QMCPy PyPI summary from its authoritative report."""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen


SOURCE_URL = (
    "https://raw.githubusercontent.com/QMCSoftware/QMCSoftware/"
    "pypi-stats/stats/pypi_downloads.md"
)
REPORT_URL = (
    "https://github.com/QMCSoftware/QMCSoftware/"
    "blob/pypi-stats/stats/pypi_downloads.md"
)
OUTPUT = Path("data/qmcpy-pypi-stats.md")

GENERATED_PATTERN = re.compile(
    r"_Auto-generated by GitHub Actions on "
    r"(?P<generated>\d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC)\._"
)
RECENT_PATTERN = re.compile(
    r"- \*\*Downloads from (?P<start>\d{4}-\d{2}-\d{2}) through "
    r"(?P<end>\d{4}-\d{2}-\d{2}) \(most recent 30 days\):\*\* "
    r"(?P<count>[\d,]+)"
)
SERIES_PATTERN = re.compile(
    r"- \*\*Downloads from (?P<start>\d{4}-\d{2}-\d{2}) through "
    r"(?P<end>\d{4}-\d{2}-\d{2}):\*\* (?P<count>[\d,]+)"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        default=SOURCE_URL,
        help="Report URL, local path, or '-' for standard input.",
    )
    parser.add_argument("--output", type=Path, default=OUTPUT)
    return parser.parse_args()


def read_source(source: str) -> str:
    if source == "-":
        return sys.stdin.read()
    if source.startswith(("https://", "http://")):
        with urlopen(source, timeout=30) as response:
            return response.read().decode("utf-8")
    return Path(source).read_text(encoding="utf-8")


def match_or_raise(pattern: re.Pattern[str], report: str, label: str) -> re.Match[str]:
    match = pattern.search(report)
    if match is None:
        raise ValueError(f"Could not find {label} in the upstream PyPI report")
    return match


def display_date(value: str) -> str:
    date = datetime.strptime(value, "%Y-%m-%d")
    return f"{date.strftime('%B')} {date.day}, {date.year}"


def build_fragment(report: str) -> str:
    generated = match_or_raise(GENERATED_PATTERN, report, "generation date")
    recent = match_or_raise(RECENT_PATTERN, report, "30-day download total")
    series = match_or_raise(SERIES_PATTERN, report, "daily-series download total")

    generated_date = display_date(generated["generated"].split()[0])
    recent_start = display_date(recent["start"])
    recent_end = display_date(recent["end"])
    series_start = display_date(series["start"])
    series_end = display_date(series["end"])

    return f"""<!-- Generated by scripts/update_qmcpy_pypi_stats.py. -->
:::: {{.pypi-stats-grid}}
::: {{.pypi-stat}}
### {recent["count"]}

downloads from {recent_start} through {recent_end} (most recent 30 days)
:::

::: {{.pypi-stat}}
### {series["count"]}

downloads from {series_start} through {series_end} (available daily series)
:::
::::

_Updated {generated_date}. Counts include automated installations, measure
recent activity rather than lifetime downloads, and come from the
[automatically generated QMCPy report]({REPORT_URL})._
"""


def main() -> None:
    args = parse_args()
    try:
        report = read_source(args.source)
    except (OSError, TimeoutError, URLError) as error:
        if args.output.exists():
            print(
                f"Warning: could not refresh {args.output}; retaining the cached "
                f"summary ({error})",
                file=sys.stderr,
            )
            return
        raise

    fragment = build_fragment(report)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(fragment, encoding="utf-8")
    print(f"Updated {args.output} from {args.source}")


if __name__ == "__main__":
    main()
